language: python
python:
    - 3.6
install: 
    - pip install -r requirements.txt
script:
    - pip install -r requirements/dev.txt
    - pip install coveralls
    - py.test --cov=app tests
after_success:
    - coveralls